#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 512

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: Syp950628
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
    suffix: .html
  task:
    execution:
      pool:
        core-size: 5
        max-size: 128
        queue-capacity: 128
        keep-alive: 60000
      thread-name-prefix: db-service-task-
  aop:
    proxy-target-class: false
mybatis:
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  level:
    cn.tedu: debug

